# Generated by Django 5.1.3 on 2024-12-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='signed_contracts/')),
                ('estimate_production_in_quintal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ml_model_estimate_production_in_quintal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimate_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ml_model_estimate_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_signed', models.BooleanField(default=False)),
                ('seller_signed_file', models.FileField(blank=True, null=True, upload_to='')),
                ('buyer_signed', models.BooleanField(default=False)),
                ('buyer_signed_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255, verbose_name='Contract Name')),
                ('contract_description', models.TextField(verbose_name='Contract Description')),
                ('contract_file', models.FileField(upload_to='contract_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('total_quintal_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CropListingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Crop Name')),
                ('crop_type', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], max_length=10, verbose_name='Crop Type')),
                ('description', models.TextField(verbose_name='Crop Description')),
                ('image', models.ImageField(upload_to='crop_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervised', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Dispute Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Dispute Status')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Admin Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(max_length=50, unique=True)),
                ('document_id', models.IntegerField(null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('signers', models.JSONField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsignResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('verification_id', models.CharField(max_length=50, unique=True)),
                ('reference_id', models.IntegerField()),
                ('document_id', models.IntegerField()),
                ('signing_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('contract', 'Contract'), ('dispute', 'Dispute'), ('payment', 'Payment'), ('profile', 'Profile')], default='info', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_file', models.FileField(upload_to='tender_applications/')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=255)),
                ('tender_description', models.TextField()),
                ('tender_file', models.FileField(upload_to='tender_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('cashfree_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cashfree_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
