# Generated by Django 5.1.3 on 2024-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
